In [93]:
import numpy as np
np.ones((2,3))
np.zeros((3,3))
np.full((2,5),7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [19]:
arr = np.arange(4).reshape(2,2)
print(arr)
cube = arr ** 3
print(cube)
add = arr + 7
print(cube)
mult = arr * 2
print(mult)

[[0 1]
 [2 3]]
[[ 0  1]
 [ 8 27]]
[[ 0  1]
 [ 8 27]]
[[0 2]
 [4 6]]

In [23]:
a = np.arange(2,19,2).reshape(3,3)
b = np.arange(9,0,-1).reshape(3,3)
c = a * b
print(c)

[[18 32 42]
 [48 50 48]
 [42 32 18]]

In [32]:
arr = np.arange(9).reshape(3,3)
print(arr)
arr[[0,1]] = arr[[1,0]]
arr[:,[0,1]] = arr[:,[1,0]]
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[4 3 5]
 [1 0 2]
 [7 6 8]]

In [34]:
arr = np.array([[2,3,5,7,11],[13,17,19,23,29]])
arr

array([[ 2,  3,  5,  7, 11],
       [13, 17, 19, 23, 29]])

In [47]:
arr = np.array([2**i for i in range(6)]).reshape(2,3)
flat = arr.flatten()
flat[0] = 100
print("Using Flatten:- \n",flat)
print(arr)

ravel = arr.ravel()
ravel[0] = 100
print("Using ravel:- \n",ravel)
print(arr)

Using Flatten:-
 [100   2   4   8  16  32]
[[ 1  2  4]
 [ 8 16 32]]
Using ravel:-
 [100   2   4   8  16  32]
[[100   2   4]
 [  8  16  32]]

In [51]:
arr = np.linspace(1.1,6.6,6).reshape(2,3)
int_arr = arr.astype(int)
print(int_arr)

[[1 2 3]
 [4 5 6]]

In [65]:
arr = np.arange(1,16).reshape(3,5)
print(arr)
row_2 = arr[[1]]
col_5 = arr[:,[4]]
row_0_1 = arr[0:2]
col_2_to_4 = arr[:,1:4]
rowCol = arr[1:3][:,[0,2,4]]
rowCol

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

array([[ 6,  8, 10],
       [11, 13, 15]])

In [74]:
arr1 = np.array([[0,1], [2,3]])
arr2 = np.array([[4,5], [6,7]])

arr3 = np.vstack((arr1,arr2))
arr4 = np.hstack((arr1,arr2))
arr5 = np.vstack((arr4,arr4))
arr6 = np.hstack((arr3,arr3))
arr5

array([[0, 1, 4, 5],
       [2, 3, 6, 7],
       [0, 1, 4, 5],
       [2, 3, 6, 7]])

In [76]:
arr = np.tile([['-','*'], ['*','-']], (4,4))
print(arr)

[['-' '*' '-' '*' '-' '*' '-' '*']
 ['*' '-' '*' '-' '*' '-' '*' '-']
 ['-' '*' '-' '*' '-' '*' '-' '*']
 ['*' '-' '*' '-' '*' '-' '*' '-']
 ['-' '*' '-' '*' '-' '*' '-' '*']
 ['*' '-' '*' '-' '*' '-' '*' '-']
 ['-' '*' '-' '*' '-' '*' '-' '*']
 ['*' '-' '*' '-' '*' '-' '*' '-']]

In [86]:
arr = np.random.randint(0,100,(5,5))
count = np.bincount(arr.flatten())
count

[83 85  9 55 77 11 46 57 70 40 24 95  6 26 99 21 19 82  4  6 41 39 32  1
 68]

array([0, 1, 0, 0, 1, 0, 2, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1])

In [87]:
# def mode(arr):
#     values, counts = np.unique(arr, return_counts=True)
#     values[np.argmax(counts)]


def median(arr):
    return np.median(arr)

def mode(arr):
    values, counts = np.unique(arr, return_counts=True)
    return values[np.argmax(counts)]


C = np.array([[[7, 8, 9],
               [7, 7, 6]],
              [[5, 7, 6],
               [7, 9, 5]]])

print("Array C:\n", C)
print("Median:", median(C))
print("Mode:", mode(C))

Array C:
 [[[7 8 9]
  [7 7 6]]

 [[5 7 6]
  [7 9 5]]]
Median: 7.0
Mode: 7

In [88]:
arr = np.random.rand(9,9,2)
sub = arr[:5,:5,:]
print(sub)

[[[0.5294504  0.35110637]
  [0.75969872 0.07968016]
  [0.5356013  0.17459916]
  [0.75862039 0.20557332]
  [0.55650673 0.6095206 ]]

 [[0.29475141 0.65468492]
  [0.36018183 0.72039839]
  [0.10049787 0.63014839]
  [0.94896229 0.03114377]
  [0.13100631 0.99193176]]

 [[0.45385411 0.61863276]
  [0.49532146 0.4563809 ]
  [0.56473866 0.04108447]
  [0.18318847 0.48408033]
  [0.71162977 0.25683931]]

 [[0.11243269 0.06480428]
  [0.66074683 0.88862744]
  [0.12149192 0.31844374]
  [0.63787128 0.78925201]
  [0.97178868 0.13964778]]

 [[0.97627981 0.09124927]
  [0.76109469 0.47537641]
  [0.04393781 0.66030112]
  [0.9091903  0.41060631]
  [0.84916455 0.91781905]]]

In [94]:
arr = np.random.rand(4,4)
sorted_arr = np.sort(arr,axis=0)
print(sorted_arr)

[[0.46000782 0.13681759 0.34638374 0.22014839]
 [0.47009954 0.28527233 0.52615719 0.58540444]
 [0.59167003 0.47742215 0.63482403 0.97611171]
 [0.79557997 0.49333306 0.64523327 0.99920565]]

In [97]:
import pandas as pd
df = pd.DataFrame({'A':[1,2,3], 'B':[4,5,6]})
series = df.iloc[:,0]
print(series)

0    1
1    2
2    3
Name: A, dtype: int64

In [125]:
temps_dict = {
    'Maxine': [98.6, 99.1, 98.9],
    'James': [97.8, 98.2, 98.0],
    'Amanda': [98.4, 98.7, 98.6]
}

df = pd.DataFrame(temps_dict, index = ["Morning", "Afternoon", "Evening"])
print(df,"\n")

           Maxine  James  Amanda
Morning      98.6   97.8    98.4
Afternoon    99.1   98.2    98.7
Evening      98.9   98.0    98.6

In [126]:
c = df['Maxine']
d = df.loc['Morning']
e = df.iloc[[0,2]]
f = df.iloc[:,[0,2]]
g = df.iloc[0:2, [0,2]]
h = df.describe()
i = df.T
j = df.sort_index(axis=1)
j

           Amanda  James  Maxine
Morning      98.4   97.8    98.6
Afternoon    98.7   98.2    99.1
Evening      98.6   98.0    98.9

In [123]:
data = [[1, 2, 3],
        [4, 5, 6]]

arr = np.array(data)
df = pd.DataFrame(data, columns=['A','B','C'])

   A  B  C
0  1  2  3
1  4  5  6

In [137]:
s = pd.Series([7,11,13,17])
# b = pd.Series([100 for _ in range(4)])
s2 = pd.Series([100.0]*5)

c = pd.Series(np.random.randint(0,101,20))
c.describe()

d_temp = pd.Series([98.6,98.9,100.2,97.2])
d_temp

e = dict(d_temp)
s1 = pd.Series(e)

0     98.6
1     98.9
2    100.2
3     97.2
dtype: float64

In [141]:
L = ['Cry', 'Apple', 'Orange', 'Sky']
s = pd.Series(L)

with_vowels = s[s.str.contains('[AEIOUaeiou]')]
starts_vowels = s[s.str.match('^[AEIOUaeiou]')]

In [142]:
s = pd.Series([1,1,3,7,88,12,88,23,3,1,9,0])
min_idx = s.idxmin()
max_idx = s.idxmax()